// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/app/diff"
)

// RendererMock is a mock implementation of diff.Renderer.
//
//	func TestSomethingThatUsesRenderer(t *testing.T) {
//
//		// make and configure a mocked diff.Renderer
//		mockedRenderer := &RendererMock{
//			ChangedFilesFunc: func(ref string, staged bool) ([]diff.FileEntry, error) {
//				panic("mock out the ChangedFiles method")
//			},
//			FileDiffFunc: func(ref string, file string, staged bool, contextLines int) ([]diff.DiffLine, error) {
//				panic("mock out the FileDiff method")
//			},
//		}
//
//		// use mockedRenderer in code that requires diff.Renderer
//		// and then make assertions.
//
//	}
type RendererMock struct {
	// ChangedFilesFunc mocks the ChangedFiles method.
	ChangedFilesFunc func(ref string, staged bool) ([]diff.FileEntry, error)

	// FileDiffFunc mocks the FileDiff method.
	FileDiffFunc func(ref string, file string, staged bool, contextLines int) ([]diff.DiffLine, error)

	// calls tracks calls to the methods.
	calls struct {
		// ChangedFiles holds details about calls to the ChangedFiles method.
		ChangedFiles []struct {
			// Ref is the ref argument value.
			Ref string
			// Staged is the staged argument value.
			Staged bool
		}
		// FileDiff holds details about calls to the FileDiff method.
		FileDiff []struct {
			// Ref is the ref argument value.
			Ref string
			// File is the file argument value.
			File string
			// Staged is the staged argument value.
			Staged bool
			// ContextLines is the contextLines argument value.
			ContextLines int
		}
	}
	lockChangedFiles sync.RWMutex
	lockFileDiff     sync.RWMutex
}

// ChangedFiles calls ChangedFilesFunc.
func (mock *RendererMock) ChangedFiles(ref string, staged bool) ([]diff.FileEntry, error) {
	if mock.ChangedFilesFunc == nil {
		panic("RendererMock.ChangedFilesFunc: method is nil but Renderer.ChangedFiles was just called")
	}
	callInfo := struct {
		Ref    string
		Staged bool
	}{
		Ref:    ref,
		Staged: staged,
	}
	mock.lockChangedFiles.Lock()
	mock.calls.ChangedFiles = append(mock.calls.ChangedFiles, callInfo)
	mock.lockChangedFiles.Unlock()
	return mock.ChangedFilesFunc(ref, staged)
}

// ChangedFilesCalls gets all the calls that were made to ChangedFiles.
// Check the length with:
//
//	len(mockedRenderer.ChangedFilesCalls())
func (mock *RendererMock) ChangedFilesCalls() []struct {
	Ref    string
	Staged bool
} {
	var calls []struct {
		Ref    string
		Staged bool
	}
	mock.lockChangedFiles.RLock()
	calls = mock.calls.ChangedFiles
	mock.lockChangedFiles.RUnlock()
	return calls
}

// FileDiff calls FileDiffFunc.
func (mock *RendererMock) FileDiff(ref string, file string, staged bool, contextLines int) ([]diff.DiffLine, error) {
	if mock.FileDiffFunc == nil {
		panic("RendererMock.FileDiffFunc: method is nil but Renderer.FileDiff was just called")
	}
	callInfo := struct {
		Ref          string
		File         string
		Staged       bool
		ContextLines int
	}{
		Ref:          ref,
		File:         file,
		Staged:       staged,
		ContextLines: contextLines,
	}
	mock.lockFileDiff.Lock()
	mock.calls.FileDiff = append(mock.calls.FileDiff, callInfo)
	mock.lockFileDiff.Unlock()
	return mock.FileDiffFunc(ref, file, staged, contextLines)
}

// FileDiffCalls gets all the calls that were made to FileDiff.
// Check the length with:
//
//	len(mockedRenderer.FileDiffCalls())
func (mock *RendererMock) FileDiffCalls() []struct {
	Ref          string
	File         string
	Staged       bool
	ContextLines int
} {
	var calls []struct {
		Ref          string
		File         string
		Staged       bool
		ContextLines int
	}
	mock.lockFileDiff.RLock()
	calls = mock.calls.FileDiff
	mock.lockFileDiff.RUnlock()
	return calls
}
