// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"sync"
)

// quitterMock is a mock implementation of quitter.
//
//	func TestSomethingThatUsesquitter(t *testing.T) {
//
//		// make and configure a mocked quitter
//		mockedquitter := &quitterMock{
//			QuitFunc: func()  {
//				panic("mock out the Quit method")
//			},
//		}
//
//		// use mockedquitter in code that requires quitter
//		// and then make assertions.
//
//	}
type quitterMock struct {
	// QuitFunc mocks the Quit method.
	QuitFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Quit holds details about calls to the Quit method.
		Quit []struct {
		}
	}
	lockQuit sync.RWMutex
}

// Quit calls QuitFunc.
func (mock *quitterMock) Quit() {
	if mock.QuitFunc == nil {
		panic("quitterMock.QuitFunc: method is nil but quitter.Quit was just called")
	}
	callInfo := struct {
	}{}
	mock.lockQuit.Lock()
	mock.calls.Quit = append(mock.calls.Quit, callInfo)
	mock.lockQuit.Unlock()
	mock.QuitFunc()
}

// QuitCalls gets all the calls that were made to Quit.
// Check the length with:
//
//	len(mockedquitter.QuitCalls())
func (mock *quitterMock) QuitCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockQuit.RLock()
	calls = mock.calls.Quit
	mock.lockQuit.RUnlock()
	return calls
}
