// Code generated by enum generator; DO NOT EDIT.
package style

import (
	"fmt"
	"strings"
)

// ColorKey is the exported type for the enum
type ColorKey struct {
	name  string
	value int
}

func (e ColorKey) String() string { return e.name }

// Index returns the underlying integer value
func (e ColorKey) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e ColorKey) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *ColorKey) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseColorKey(string(text))
	return err
}

// _colorKeyParseMap is used for efficient string to enum conversion
var _colorKeyParseMap = map[string]ColorKey{
	"unknown":      ColorKeyUnknown,
	"accentfg":     ColorKeyAccentFg,
	"mutedfg":      ColorKeyMutedFg,
	"annotationfg": ColorKeyAnnotationFg,
	"statusfg":     ColorKeyStatusFg,
	"treepanebg":   ColorKeyTreePaneBg,
	"diffpanebg":   ColorKeyDiffPaneBg,
	"addlinebg":    ColorKeyAddLineBg,
	"removelinebg": ColorKeyRemoveLineBg,
	"modifylinebg": ColorKeyModifyLineBg,
	"wordaddbg":    ColorKeyWordAddBg,
	"wordremovebg": ColorKeyWordRemoveBg,
	"searchbg":     ColorKeySearchBg,
	"addlinefg":    ColorKeyAddLineFg,
	"removelinefg": ColorKeyRemoveLineFg,
	"modifylinefg": ColorKeyModifyLineFg,
	"searchfg":     ColorKeySearchFg,
	"normalfg":     ColorKeyNormalFg,
	"selectedfg":   ColorKeySelectedFg,
}

// ParseColorKey converts string to colorKey enum value.
// Parsing is always case-insensitive.
func ParseColorKey(v string) (ColorKey, error) {
	if val, ok := _colorKeyParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return ColorKey{}, fmt.Errorf("invalid colorKey: %s", v)
}

// MustColorKey is like ParseColorKey but panics if string is invalid
func MustColorKey(v string) ColorKey {
	r, err := ParseColorKey(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for colorKey values
var (
	// zero value sentinel
	ColorKeyUnknown      = ColorKey{name: "Unknown", value: 0}
	ColorKeyAccentFg     = ColorKey{name: "AccentFg", value: 1}
	ColorKeyMutedFg      = ColorKey{name: "MutedFg", value: 2}
	ColorKeyAnnotationFg = ColorKey{name: "AnnotationFg", value: 3}
	// internal fallback: StatusFg || MutedFg
	ColorKeyStatusFg     = ColorKey{name: "StatusFg", value: 4}
	ColorKeyTreePaneBg   = ColorKey{name: "TreePaneBg", value: 5}
	ColorKeyDiffPaneBg   = ColorKey{name: "DiffPaneBg", value: 6}
	ColorKeyAddLineBg    = ColorKey{name: "AddLineBg", value: 7}
	ColorKeyRemoveLineBg = ColorKey{name: "RemoveLineBg", value: 8}
	ColorKeyModifyLineBg = ColorKey{name: "ModifyLineBg", value: 9}
	ColorKeyWordAddBg    = ColorKey{name: "WordAddBg", value: 10}
	ColorKeyWordRemoveBg = ColorKey{name: "WordRemoveBg", value: 11}
	ColorKeySearchBg     = ColorKey{name: "SearchBg", value: 12}
	ColorKeyAddLineFg    = ColorKey{name: "AddLineFg", value: 13}
	ColorKeyRemoveLineFg = ColorKey{name: "RemoveLineFg", value: 14}
	ColorKeyModifyLineFg = ColorKey{name: "ModifyLineFg", value: 15}
	ColorKeySearchFg     = ColorKey{name: "SearchFg", value: 16}
	ColorKeyNormalFg     = ColorKey{name: "NormalFg", value: 17}
	ColorKeySelectedFg   = ColorKey{name: "SelectedFg", value: 18}
)

// ColorKeyValues contains all possible enum values
var ColorKeyValues = []ColorKey{
	ColorKeyUnknown,
	ColorKeyAccentFg,
	ColorKeyMutedFg,
	ColorKeyAnnotationFg,
	ColorKeyStatusFg,
	ColorKeyTreePaneBg,
	ColorKeyDiffPaneBg,
	ColorKeyAddLineBg,
	ColorKeyRemoveLineBg,
	ColorKeyModifyLineBg,
	ColorKeyWordAddBg,
	ColorKeyWordRemoveBg,
	ColorKeySearchBg,
	ColorKeyAddLineFg,
	ColorKeyRemoveLineFg,
	ColorKeyModifyLineFg,
	ColorKeySearchFg,
	ColorKeyNormalFg,
	ColorKeySelectedFg,
}

// ColorKeyNames contains all possible enum names
var ColorKeyNames = []string{
	"Unknown",
	"AccentFg",
	"MutedFg",
	"AnnotationFg",
	"StatusFg",
	"TreePaneBg",
	"DiffPaneBg",
	"AddLineBg",
	"RemoveLineBg",
	"ModifyLineBg",
	"WordAddBg",
	"WordRemoveBg",
	"SearchBg",
	"AddLineFg",
	"RemoveLineFg",
	"ModifyLineFg",
	"SearchFg",
	"NormalFg",
	"SelectedFg",
}

// ColorKeyIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all ColorKey values in declaration order. Example:
//
//	for v := range ColorKeyIter() {
//	    // use v
//	}
func ColorKeyIter() func(yield func(ColorKey) bool) {
	return func(yield func(ColorKey) bool) {
		for _, v := range ColorKeyValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ colorKey = colorKey(0)
	// This avoids "defined but not used" linter error for colorKeyUnknown
	var _ colorKey = colorKeyUnknown
	// This avoids "defined but not used" linter error for colorKeyAccentFg
	var _ colorKey = colorKeyAccentFg
	// This avoids "defined but not used" linter error for colorKeyMutedFg
	var _ colorKey = colorKeyMutedFg
	// This avoids "defined but not used" linter error for colorKeyAnnotationFg
	var _ colorKey = colorKeyAnnotationFg
	// This avoids "defined but not used" linter error for colorKeyStatusFg
	var _ colorKey = colorKeyStatusFg
	// This avoids "defined but not used" linter error for colorKeyTreePaneBg
	var _ colorKey = colorKeyTreePaneBg
	// This avoids "defined but not used" linter error for colorKeyDiffPaneBg
	var _ colorKey = colorKeyDiffPaneBg
	// This avoids "defined but not used" linter error for colorKeyAddLineBg
	var _ colorKey = colorKeyAddLineBg
	// This avoids "defined but not used" linter error for colorKeyRemoveLineBg
	var _ colorKey = colorKeyRemoveLineBg
	// This avoids "defined but not used" linter error for colorKeyModifyLineBg
	var _ colorKey = colorKeyModifyLineBg
	// This avoids "defined but not used" linter error for colorKeyWordAddBg
	var _ colorKey = colorKeyWordAddBg
	// This avoids "defined but not used" linter error for colorKeyWordRemoveBg
	var _ colorKey = colorKeyWordRemoveBg
	// This avoids "defined but not used" linter error for colorKeySearchBg
	var _ colorKey = colorKeySearchBg
	// This avoids "defined but not used" linter error for colorKeyAddLineFg
	var _ colorKey = colorKeyAddLineFg
	// This avoids "defined but not used" linter error for colorKeyRemoveLineFg
	var _ colorKey = colorKeyRemoveLineFg
	// This avoids "defined but not used" linter error for colorKeyModifyLineFg
	var _ colorKey = colorKeyModifyLineFg
	// This avoids "defined but not used" linter error for colorKeySearchFg
	var _ colorKey = colorKeySearchFg
	// This avoids "defined but not used" linter error for colorKeyNormalFg
	var _ colorKey = colorKeyNormalFg
	// This avoids "defined but not used" linter error for colorKeySelectedFg
	var _ colorKey = colorKeySelectedFg
	return true
}()
