// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/diff"
)

// SyntaxHighlighterMock is a mock implementation of ui.SyntaxHighlighter.
//
//	func TestSomethingThatUsesSyntaxHighlighter(t *testing.T) {
//
//		// make and configure a mocked ui.SyntaxHighlighter
//		mockedSyntaxHighlighter := &SyntaxHighlighterMock{
//			HighlightLinesFunc: func(filename string, lines []diff.DiffLine) []string {
//				panic("mock out the HighlightLines method")
//			},
//		}
//
//		// use mockedSyntaxHighlighter in code that requires ui.SyntaxHighlighter
//		// and then make assertions.
//
//	}
type SyntaxHighlighterMock struct {
	// HighlightLinesFunc mocks the HighlightLines method.
	HighlightLinesFunc func(filename string, lines []diff.DiffLine) []string

	// calls tracks calls to the methods.
	calls struct {
		// HighlightLines holds details about calls to the HighlightLines method.
		HighlightLines []struct {
			// Filename is the filename argument value.
			Filename string
			// Lines is the lines argument value.
			Lines []diff.DiffLine
		}
	}
	lockHighlightLines sync.RWMutex
}

// HighlightLines calls HighlightLinesFunc.
func (mock *SyntaxHighlighterMock) HighlightLines(filename string, lines []diff.DiffLine) []string {
	if mock.HighlightLinesFunc == nil {
		panic("SyntaxHighlighterMock.HighlightLinesFunc: method is nil but SyntaxHighlighter.HighlightLines was just called")
	}
	callInfo := struct {
		Filename string
		Lines    []diff.DiffLine
	}{
		Filename: filename,
		Lines:    lines,
	}
	mock.lockHighlightLines.Lock()
	mock.calls.HighlightLines = append(mock.calls.HighlightLines, callInfo)
	mock.lockHighlightLines.Unlock()
	return mock.HighlightLinesFunc(filename, lines)
}

// HighlightLinesCalls gets all the calls that were made to HighlightLines.
// Check the length with:
//
//	len(mockedSyntaxHighlighter.HighlightLinesCalls())
func (mock *SyntaxHighlighterMock) HighlightLinesCalls() []struct {
	Filename string
	Lines    []diff.DiffLine
} {
	var calls []struct {
		Filename string
		Lines    []diff.DiffLine
	}
	mock.lockHighlightLines.RLock()
	calls = mock.calls.HighlightLines
	mock.lockHighlightLines.RUnlock()
	return calls
}
