// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/diff"
)

// DiffRendererMock is a mock implementation of diff.DiffRenderer.
//
//	func TestSomethingThatUsesDiffRenderer(t *testing.T) {
//
//		// make and configure a mocked diff.DiffRenderer
//		mockedDiffRenderer := &DiffRendererMock{
//			ChangedFilesFunc: func(ref string, staged bool) ([]string, error) {
//				panic("mock out the ChangedFiles method")
//			},
//			FileDiffFunc: func(ref string, file string, staged bool) ([]diff.DiffLine, error) {
//				panic("mock out the FileDiff method")
//			},
//		}
//
//		// use mockedDiffRenderer in code that requires diff.DiffRenderer
//		// and then make assertions.
//
//	}
type DiffRendererMock struct {
	// ChangedFilesFunc mocks the ChangedFiles method.
	ChangedFilesFunc func(ref string, staged bool) ([]string, error)

	// FileDiffFunc mocks the FileDiff method.
	FileDiffFunc func(ref string, file string, staged bool) ([]diff.DiffLine, error)

	// calls tracks calls to the methods.
	calls struct {
		// ChangedFiles holds details about calls to the ChangedFiles method.
		ChangedFiles []struct {
			// Ref is the ref argument value.
			Ref string
			// Staged is the staged argument value.
			Staged bool
		}
		// FileDiff holds details about calls to the FileDiff method.
		FileDiff []struct {
			// Ref is the ref argument value.
			Ref string
			// File is the file argument value.
			File string
			// Staged is the staged argument value.
			Staged bool
		}
	}
	lockChangedFiles sync.RWMutex
	lockFileDiff     sync.RWMutex
}

// ChangedFiles calls ChangedFilesFunc.
func (mock *DiffRendererMock) ChangedFiles(ref string, staged bool) ([]string, error) {
	if mock.ChangedFilesFunc == nil {
		panic("DiffRendererMock.ChangedFilesFunc: method is nil but DiffRenderer.ChangedFiles was just called")
	}
	callInfo := struct {
		Ref    string
		Staged bool
	}{
		Ref:    ref,
		Staged: staged,
	}
	mock.lockChangedFiles.Lock()
	mock.calls.ChangedFiles = append(mock.calls.ChangedFiles, callInfo)
	mock.lockChangedFiles.Unlock()
	return mock.ChangedFilesFunc(ref, staged)
}

// ChangedFilesCalls gets all the calls that were made to ChangedFiles.
// Check the length with:
//
//	len(mockedDiffRenderer.ChangedFilesCalls())
func (mock *DiffRendererMock) ChangedFilesCalls() []struct {
	Ref    string
	Staged bool
} {
	var calls []struct {
		Ref    string
		Staged bool
	}
	mock.lockChangedFiles.RLock()
	calls = mock.calls.ChangedFiles
	mock.lockChangedFiles.RUnlock()
	return calls
}

// FileDiff calls FileDiffFunc.
func (mock *DiffRendererMock) FileDiff(ref string, file string, staged bool) ([]diff.DiffLine, error) {
	if mock.FileDiffFunc == nil {
		panic("DiffRendererMock.FileDiffFunc: method is nil but DiffRenderer.FileDiff was just called")
	}
	callInfo := struct {
		Ref    string
		File   string
		Staged bool
	}{
		Ref:    ref,
		File:   file,
		Staged: staged,
	}
	mock.lockFileDiff.Lock()
	mock.calls.FileDiff = append(mock.calls.FileDiff, callInfo)
	mock.lockFileDiff.Unlock()
	return mock.FileDiffFunc(ref, file, staged)
}

// FileDiffCalls gets all the calls that were made to FileDiff.
// Check the length with:
//
//	len(mockedDiffRenderer.FileDiffCalls())
func (mock *DiffRendererMock) FileDiffCalls() []struct {
	Ref    string
	File   string
	Staged bool
} {
	var calls []struct {
		Ref    string
		File   string
		Staged bool
	}
	mock.lockFileDiff.RLock()
	calls = mock.calls.FileDiff
	mock.lockFileDiff.RUnlock()
	return calls
}
