// Code generated by enum generator; DO NOT EDIT.
package sidepane

import (
	"fmt"
	"strings"
)

// Direction is the exported type for the enum
type Direction struct {
	name  string
	value int
}

func (e Direction) String() string { return e.name }

// Index returns the underlying integer value
func (e Direction) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e Direction) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *Direction) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseDirection(string(text))
	return err
}

// _directionParseMap is used for efficient string to enum conversion
var _directionParseMap = map[string]Direction{
	"unknown": DirectionUnknown,
	"next":    DirectionNext,
	"prev":    DirectionPrev,
}

// ParseDirection converts string to direction enum value.
// Parsing is always case-insensitive.
func ParseDirection(v string) (Direction, error) {
	if val, ok := _directionParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return Direction{}, fmt.Errorf("invalid direction: %s", v)
}

// MustDirection is like ParseDirection but panics if string is invalid
func MustDirection(v string) Direction {
	r, err := ParseDirection(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for direction values
var (
	// zero value sentinel
	DirectionUnknown = Direction{name: "Unknown", value: 0}
	// forward / next
	DirectionNext = Direction{name: "Next", value: 1}
	// backward / previous
	DirectionPrev = Direction{name: "Prev", value: 2}
)

// DirectionValues contains all possible enum values
var DirectionValues = []Direction{
	DirectionUnknown,
	DirectionNext,
	DirectionPrev,
}

// DirectionNames contains all possible enum names
var DirectionNames = []string{
	"Unknown",
	"Next",
	"Prev",
}

// DirectionIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all Direction values in declaration order. Example:
//
//	for v := range DirectionIter() {
//	    // use v
//	}
func DirectionIter() func(yield func(Direction) bool) {
	return func(yield func(Direction) bool) {
		for _, v := range DirectionValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ direction = direction(0)
	// This avoids "defined but not used" linter error for directionUnknown
	var _ direction = directionUnknown
	// This avoids "defined but not used" linter error for directionNext
	var _ direction = directionNext
	// This avoids "defined but not used" linter error for directionPrev
	var _ direction = directionPrev
	return true
}()
