// Code generated by enum generator; DO NOT EDIT.
package sidepane

import (
	"fmt"
	"strings"
)

// Motion is the exported type for the enum
type Motion struct {
	name  string
	value int
}

func (e Motion) String() string { return e.name }

// Index returns the underlying integer value
func (e Motion) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e Motion) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *Motion) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseMotion(string(text))
	return err
}

// _motionParseMap is used for efficient string to enum conversion
var _motionParseMap = map[string]Motion{
	"unknown":  MotionUnknown,
	"up":       MotionUp,
	"down":     MotionDown,
	"pageup":   MotionPageUp,
	"pagedown": MotionPageDown,
	"first":    MotionFirst,
	"last":     MotionLast,
}

// ParseMotion converts string to motion enum value.
// Parsing is always case-insensitive.
func ParseMotion(v string) (Motion, error) {
	if val, ok := _motionParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return Motion{}, fmt.Errorf("invalid motion: %s", v)
}

// MustMotion is like ParseMotion but panics if string is invalid
func MustMotion(v string) Motion {
	r, err := ParseMotion(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for motion values
var (
	// zero value sentinel
	MotionUnknown = Motion{name: "Unknown", value: 0}
	// single step up
	MotionUp = Motion{name: "Up", value: 1}
	// single step down
	MotionDown = Motion{name: "Down", value: 2}
	// page up — uses count[0] from variadic
	MotionPageUp = Motion{name: "PageUp", value: 3}
	// page down — uses count[0] from variadic
	MotionPageDown = Motion{name: "PageDown", value: 4}
	// jump to first entry
	MotionFirst = Motion{name: "First", value: 5}
	// jump to last entry
	MotionLast = Motion{name: "Last", value: 6}
)

// MotionValues contains all possible enum values
var MotionValues = []Motion{
	MotionUnknown,
	MotionUp,
	MotionDown,
	MotionPageUp,
	MotionPageDown,
	MotionFirst,
	MotionLast,
}

// MotionNames contains all possible enum names
var MotionNames = []string{
	"Unknown",
	"Up",
	"Down",
	"PageUp",
	"PageDown",
	"First",
	"Last",
}

// MotionIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all Motion values in declaration order. Example:
//
//	for v := range MotionIter() {
//	    // use v
//	}
func MotionIter() func(yield func(Motion) bool) {
	return func(yield func(Motion) bool) {
		for _, v := range MotionValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ motion = motion(0)
	// This avoids "defined but not used" linter error for motionUnknown
	var _ motion = motionUnknown
	// This avoids "defined but not used" linter error for motionUp
	var _ motion = motionUp
	// This avoids "defined but not used" linter error for motionDown
	var _ motion = motionDown
	// This avoids "defined but not used" linter error for motionPageUp
	var _ motion = motionPageUp
	// This avoids "defined but not used" linter error for motionPageDown
	var _ motion = motionPageDown
	// This avoids "defined but not used" linter error for motionFirst
	var _ motion = motionFirst
	// This avoids "defined but not used" linter error for motionLast
	var _ motion = motionLast
	return true
}()
