// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// AnnotationMarkdownMock is a mock implementation of ui.AnnotationMarkdown.
//
//	func TestSomethingThatUsesAnnotationMarkdown(t *testing.T) {
//
//		// make and configure a mocked ui.AnnotationMarkdown
//		mockedAnnotationMarkdown := &AnnotationMarkdownMock{
//			RenderFunc: func(body string, width int) []string {
//				panic("mock out the Render method")
//			},
//		}
//
//		// use mockedAnnotationMarkdown in code that requires ui.AnnotationMarkdown
//		// and then make assertions.
//
//	}
type AnnotationMarkdownMock struct {
	// RenderFunc mocks the Render method.
	RenderFunc func(body string, width int) []string

	// calls tracks calls to the methods.
	calls struct {
		// Render holds details about calls to the Render method.
		Render []struct {
			// Body is the body argument value.
			Body string
			// Width is the width argument value.
			Width int
		}
	}
	lockRender sync.RWMutex
}

// Render calls RenderFunc.
func (mock *AnnotationMarkdownMock) Render(body string, width int) []string {
	if mock.RenderFunc == nil {
		panic("AnnotationMarkdownMock.RenderFunc: method is nil but AnnotationMarkdown.Render was just called")
	}
	callInfo := struct {
		Body  string
		Width int
	}{
		Body:  body,
		Width: width,
	}
	mock.lockRender.Lock()
	mock.calls.Render = append(mock.calls.Render, callInfo)
	mock.lockRender.Unlock()
	return mock.RenderFunc(body, width)
}

// RenderCalls gets all the calls that were made to Render.
// Check the length with:
//
//	len(mockedAnnotationMarkdown.RenderCalls())
func (mock *AnnotationMarkdownMock) RenderCalls() []struct {
	Body  string
	Width int
} {
	var calls []struct {
		Body  string
		Width int
	}
	mock.lockRender.RLock()
	calls = mock.calls.Render
	mock.lockRender.RUnlock()
	return calls
}
