// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/app/diff"
)

// BlamerMock is a mock implementation of ui.Blamer.
//
//	func TestSomethingThatUsesBlamer(t *testing.T) {
//
//		// make and configure a mocked ui.Blamer
//		mockedBlamer := &BlamerMock{
//			FileBlameFunc: func(ref string, file string, staged bool) (map[int]diff.BlameLine, error) {
//				panic("mock out the FileBlame method")
//			},
//		}
//
//		// use mockedBlamer in code that requires ui.Blamer
//		// and then make assertions.
//
//	}
type BlamerMock struct {
	// FileBlameFunc mocks the FileBlame method.
	FileBlameFunc func(ref string, file string, staged bool) (map[int]diff.BlameLine, error)

	// calls tracks calls to the methods.
	calls struct {
		// FileBlame holds details about calls to the FileBlame method.
		FileBlame []struct {
			// Ref is the ref argument value.
			Ref string
			// File is the file argument value.
			File string
			// Staged is the staged argument value.
			Staged bool
		}
	}
	lockFileBlame sync.RWMutex
}

// FileBlame calls FileBlameFunc.
func (mock *BlamerMock) FileBlame(ref string, file string, staged bool) (map[int]diff.BlameLine, error) {
	if mock.FileBlameFunc == nil {
		panic("BlamerMock.FileBlameFunc: method is nil but Blamer.FileBlame was just called")
	}
	callInfo := struct {
		Ref    string
		File   string
		Staged bool
	}{
		Ref:    ref,
		File:   file,
		Staged: staged,
	}
	mock.lockFileBlame.Lock()
	mock.calls.FileBlame = append(mock.calls.FileBlame, callInfo)
	mock.lockFileBlame.Unlock()
	return mock.FileBlameFunc(ref, file, staged)
}

// FileBlameCalls gets all the calls that were made to FileBlame.
// Check the length with:
//
//	len(mockedBlamer.FileBlameCalls())
func (mock *BlamerMock) FileBlameCalls() []struct {
	Ref    string
	File   string
	Staged bool
} {
	var calls []struct {
		Ref    string
		File   string
		Staged bool
	}
	mock.lockFileBlame.RLock()
	calls = mock.calls.FileBlame
	mock.lockFileBlame.RUnlock()
	return calls
}
