// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/app/diff"
)

// commitLogSourceMock is a mock implementation of ui.commitLogSource.
//
//	func TestSomethingThatUsescommitLogSource(t *testing.T) {
//
//		// make and configure a mocked ui.commitLogSource
//		mockedcommitLogSource := &commitLogSourceMock{
//			CommitLogFunc: func(ref string) ([]diff.CommitInfo, error) {
//				panic("mock out the CommitLog method")
//			},
//		}
//
//		// use mockedcommitLogSource in code that requires ui.commitLogSource
//		// and then make assertions.
//
//	}
type commitLogSourceMock struct {
	// CommitLogFunc mocks the CommitLog method.
	CommitLogFunc func(ref string) ([]diff.CommitInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// CommitLog holds details about calls to the CommitLog method.
		CommitLog []struct {
			// Ref is the ref argument value.
			Ref string
		}
	}
	lockCommitLog sync.RWMutex
}

// CommitLog calls CommitLogFunc.
func (mock *commitLogSourceMock) CommitLog(ref string) ([]diff.CommitInfo, error) {
	if mock.CommitLogFunc == nil {
		panic("commitLogSourceMock.CommitLogFunc: method is nil but commitLogSource.CommitLog was just called")
	}
	callInfo := struct {
		Ref string
	}{
		Ref: ref,
	}
	mock.lockCommitLog.Lock()
	mock.calls.CommitLog = append(mock.calls.CommitLog, callInfo)
	mock.lockCommitLog.Unlock()
	return mock.CommitLogFunc(ref)
}

// CommitLogCalls gets all the calls that were made to CommitLog.
// Check the length with:
//
//	len(mockedcommitLogSource.CommitLogCalls())
func (mock *commitLogSourceMock) CommitLogCalls() []struct {
	Ref string
} {
	var calls []struct {
		Ref string
	}
	mock.lockCommitLog.RLock()
	calls = mock.calls.CommitLog
	mock.lockCommitLog.RUnlock()
	return calls
}
