// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"os/exec"
	"sync"
)

// ExternalEditorMock is a mock implementation of ui.ExternalEditor.
//
//	func TestSomethingThatUsesExternalEditor(t *testing.T) {
//
//		// make and configure a mocked ui.ExternalEditor
//		mockedExternalEditor := &ExternalEditorMock{
//			CommandFunc: func(content string) (*exec.Cmd, func(error) (string, error), error) {
//				panic("mock out the Command method")
//			},
//		}
//
//		// use mockedExternalEditor in code that requires ui.ExternalEditor
//		// and then make assertions.
//
//	}
type ExternalEditorMock struct {
	// CommandFunc mocks the Command method.
	CommandFunc func(content string) (*exec.Cmd, func(error) (string, error), error)
	// SourceCommandFunc mocks the SourceCommand method.
	SourceCommandFunc func(path string, line int) (*exec.Cmd, error)

	// calls tracks calls to the methods.
	calls struct {
		// Command holds details about calls to the Command method.
		Command []struct {
			// Content is the content argument value.
			Content string
		}
		// SourceCommand holds details about calls to the SourceCommand method.
		SourceCommand []struct {
			// Path is the path argument value.
			Path string
			// Line is the line argument value.
			Line int
		}
	}
	lockCommand       sync.RWMutex
	lockSourceCommand sync.RWMutex
}

// Command calls CommandFunc.
func (mock *ExternalEditorMock) Command(content string) (*exec.Cmd, func(error) (string, error), error) {
	if mock.CommandFunc == nil {
		panic("ExternalEditorMock.CommandFunc: method is nil but ExternalEditor.Command was just called")
	}
	callInfo := struct {
		Content string
	}{
		Content: content,
	}
	mock.lockCommand.Lock()
	mock.calls.Command = append(mock.calls.Command, callInfo)
	mock.lockCommand.Unlock()
	return mock.CommandFunc(content)
}

// SourceCommand calls SourceCommandFunc.
func (mock *ExternalEditorMock) SourceCommand(path string, line int) (*exec.Cmd, error) {
	if mock.SourceCommandFunc == nil {
		panic("ExternalEditorMock.SourceCommandFunc: method is nil but ExternalEditor.SourceCommand was just called")
	}
	callInfo := struct {
		Path string
		Line int
	}{
		Path: path,
		Line: line,
	}
	mock.lockSourceCommand.Lock()
	mock.calls.SourceCommand = append(mock.calls.SourceCommand, callInfo)
	mock.lockSourceCommand.Unlock()
	return mock.SourceCommandFunc(path, line)
}

// CommandCalls gets all the calls that were made to Command.
// Check the length with:
//
//	len(mockedExternalEditor.CommandCalls())
func (mock *ExternalEditorMock) CommandCalls() []struct {
	Content string
} {
	var calls []struct {
		Content string
	}
	mock.lockCommand.RLock()
	calls = mock.calls.Command
	mock.lockCommand.RUnlock()
	return calls
}

// SourceCommandCalls gets all the calls that were made to SourceCommand.
// Check the length with:
//
//	len(mockedExternalEditor.SourceCommandCalls())
func (mock *ExternalEditorMock) SourceCommandCalls() []struct {
	Path string
	Line int
} {
	var calls []struct {
		Path string
		Line int
	}
	mock.lockSourceCommand.RLock()
	calls = mock.calls.SourceCommand
	mock.lockSourceCommand.RUnlock()
	return calls
}
