// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/app/diff"
)

// RendererMock is a mock implementation of ui.Renderer.
//
//	func TestSomethingThatUsesRenderer(t *testing.T) {
//
//		// make and configure a mocked ui.Renderer
//		mockedRenderer := &RendererMock{
//			ChangedFilesFunc: func(ref string, staged bool) ([]diff.FileEntry, error) {
//				panic("mock out the ChangedFiles method")
//			},
//			FileDiffFunc: func(ref string, file string, staged bool) ([]diff.DiffLine, error) {
//				panic("mock out the FileDiff method")
//			},
//			UntrackedFilesFunc: func() ([]string, error) {
//				panic("mock out the UntrackedFiles method")
//			},
//		}
//
//		// use mockedRenderer in code that requires ui.Renderer
//		// and then make assertions.
//
//	}
type RendererMock struct {
	// ChangedFilesFunc mocks the ChangedFiles method.
	ChangedFilesFunc func(ref string, staged bool) ([]diff.FileEntry, error)

	// FileDiffFunc mocks the FileDiff method.
	FileDiffFunc func(ref string, file string, staged bool) ([]diff.DiffLine, error)

	// UntrackedFilesFunc mocks the UntrackedFiles method.
	UntrackedFilesFunc func() ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ChangedFiles holds details about calls to the ChangedFiles method.
		ChangedFiles []struct {
			// Ref is the ref argument value.
			Ref string
			// Staged is the staged argument value.
			Staged bool
		}
		// FileDiff holds details about calls to the FileDiff method.
		FileDiff []struct {
			// Ref is the ref argument value.
			Ref string
			// File is the file argument value.
			File string
			// Staged is the staged argument value.
			Staged bool
		}
		// UntrackedFiles holds details about calls to the UntrackedFiles method.
		UntrackedFiles []struct{}
	}
	lockChangedFiles  sync.RWMutex
	lockFileDiff      sync.RWMutex
	lockUntrackedFiles sync.RWMutex
}

// ChangedFiles calls ChangedFilesFunc.
func (mock *RendererMock) ChangedFiles(ref string, staged bool) ([]diff.FileEntry, error) {
	if mock.ChangedFilesFunc == nil {
		panic("RendererMock.ChangedFilesFunc: method is nil but Renderer.ChangedFiles was just called")
	}
	callInfo := struct {
		Ref    string
		Staged bool
	}{
		Ref:    ref,
		Staged: staged,
	}
	mock.lockChangedFiles.Lock()
	mock.calls.ChangedFiles = append(mock.calls.ChangedFiles, callInfo)
	mock.lockChangedFiles.Unlock()
	return mock.ChangedFilesFunc(ref, staged)
}

// ChangedFilesCalls gets all the calls that were made to ChangedFiles.
// Check the length with:
//
//	len(mockedRenderer.ChangedFilesCalls())
func (mock *RendererMock) ChangedFilesCalls() []struct {
	Ref    string
	Staged bool
} {
	var calls []struct {
		Ref    string
		Staged bool
	}
	mock.lockChangedFiles.RLock()
	calls = mock.calls.ChangedFiles
	mock.lockChangedFiles.RUnlock()
	return calls
}

// FileDiff calls FileDiffFunc.
func (mock *RendererMock) FileDiff(ref string, file string, staged bool) ([]diff.DiffLine, error) {
	if mock.FileDiffFunc == nil {
		panic("RendererMock.FileDiffFunc: method is nil but Renderer.FileDiff was just called")
	}
	callInfo := struct {
		Ref    string
		File   string
		Staged bool
	}{
		Ref:    ref,
		File:   file,
		Staged: staged,
	}
	mock.lockFileDiff.Lock()
	mock.calls.FileDiff = append(mock.calls.FileDiff, callInfo)
	mock.lockFileDiff.Unlock()
	return mock.FileDiffFunc(ref, file, staged)
}

// FileDiffCalls gets all the calls that were made to FileDiff.
// Check the length with:
//
//	len(mockedRenderer.FileDiffCalls())
func (mock *RendererMock) FileDiffCalls() []struct {
	Ref    string
	File   string
	Staged bool
} {
	var calls []struct {
		Ref    string
		File   string
		Staged bool
	}
	mock.lockFileDiff.RLock()
	calls = mock.calls.FileDiff
	mock.lockFileDiff.RUnlock()
	return calls
}

// UntrackedFiles calls UntrackedFilesFunc.
func (mock *RendererMock) UntrackedFiles() ([]string, error) {
	if mock.UntrackedFilesFunc == nil {
		panic("RendererMock.UntrackedFilesFunc: method is nil but Renderer.UntrackedFiles was just called")
	}
	callInfo := struct{}{}
	mock.lockUntrackedFiles.Lock()
	mock.calls.UntrackedFiles = append(mock.calls.UntrackedFiles, callInfo)
	mock.lockUntrackedFiles.Unlock()
	return mock.UntrackedFilesFunc()
}

// UntrackedFilesCalls gets all the calls that were made to UntrackedFiles.
// Check the length with:
//
//	len(mockedRenderer.UntrackedFilesCalls())
func (mock *RendererMock) UntrackedFilesCalls() []struct{} {
	var calls []struct{}
	mock.lockUntrackedFiles.RLock()
	calls = mock.calls.UntrackedFiles
	mock.lockUntrackedFiles.RUnlock()
	return calls
}
