// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// sgrProcessorMock is a mock implementation of ui.sgrProcessor.
//
//	func TestSomethingThatUsessgrProcessor(t *testing.T) {
//
//		// make and configure a mocked ui.sgrProcessor
//		mockedsgrProcessor := &sgrProcessorMock{
//			ReemitFunc: func(lines []string) []string {
//				panic("mock out the Reemit method")
//			},
//		}
//
//		// use mockedsgrProcessor in code that requires ui.sgrProcessor
//		// and then make assertions.
//
//	}
type sgrProcessorMock struct {
	// ReemitFunc mocks the Reemit method.
	ReemitFunc func(lines []string) []string

	// calls tracks calls to the methods.
	calls struct {
		// Reemit holds details about calls to the Reemit method.
		Reemit []struct {
			// Lines is the lines argument value.
			Lines []string
		}
	}
	lockReemit sync.RWMutex
}

// Reemit calls ReemitFunc.
func (mock *sgrProcessorMock) Reemit(lines []string) []string {
	if mock.ReemitFunc == nil {
		panic("sgrProcessorMock.ReemitFunc: method is nil but sgrProcessor.Reemit was just called")
	}
	callInfo := struct {
		Lines []string
	}{
		Lines: lines,
	}
	mock.lockReemit.Lock()
	mock.calls.Reemit = append(mock.calls.Reemit, callInfo)
	mock.lockReemit.Unlock()
	return mock.ReemitFunc(lines)
}

// ReemitCalls gets all the calls that were made to Reemit.
// Check the length with:
//
//	len(mockedsgrProcessor.ReemitCalls())
func (mock *sgrProcessorMock) ReemitCalls() []struct {
	Lines []string
} {
	var calls []struct {
		Lines []string
	}
	mock.lockReemit.RLock()
	calls = mock.calls.Reemit
	mock.lockReemit.RUnlock()
	return calls
}
