// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/app/diff"
)

// styleRendererMock is a mock implementation of ui.styleRenderer.
//
//	func TestSomethingThatUsesstyleRenderer(t *testing.T) {
//
//		// make and configure a mocked ui.styleRenderer
//		mockedstyleRenderer := &styleRendererMock{
//			AnnotationInlineFunc: func(text string) string {
//				panic("mock out the AnnotationInline method")
//			},
//			DiffCursorFunc: func(noColors bool) string {
//				panic("mock out the DiffCursor method")
//			},
//			FileAnnotationMarkFunc: func() string {
//				panic("mock out the FileAnnotationMark method")
//			},
//			FileReviewedMarkFunc: func() string {
//				panic("mock out the FileReviewedMark method")
//			},
//			FileStatusMarkFunc: func(status diff.FileStatus) string {
//				panic("mock out the FileStatusMark method")
//			},
//			StatusBarSeparatorFunc: func() string {
//				panic("mock out the StatusBarSeparator method")
//			},
//		}
//
//		// use mockedstyleRenderer in code that requires ui.styleRenderer
//		// and then make assertions.
//
//	}
type styleRendererMock struct {
	// AnnotationInlineFunc mocks the AnnotationInline method.
	AnnotationInlineFunc func(text string) string

	// DiffCursorFunc mocks the DiffCursor method.
	DiffCursorFunc func(noColors bool) string

	// FileAnnotationMarkFunc mocks the FileAnnotationMark method.
	FileAnnotationMarkFunc func() string

	// FileReviewedMarkFunc mocks the FileReviewedMark method.
	FileReviewedMarkFunc func() string

	// FileStatusMarkFunc mocks the FileStatusMark method.
	FileStatusMarkFunc func(status diff.FileStatus) string

	// StatusBarSeparatorFunc mocks the StatusBarSeparator method.
	StatusBarSeparatorFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// AnnotationInline holds details about calls to the AnnotationInline method.
		AnnotationInline []struct {
			// Text is the text argument value.
			Text string
		}
		// DiffCursor holds details about calls to the DiffCursor method.
		DiffCursor []struct {
			// NoColors is the noColors argument value.
			NoColors bool
		}
		// FileAnnotationMark holds details about calls to the FileAnnotationMark method.
		FileAnnotationMark []struct {
		}
		// FileReviewedMark holds details about calls to the FileReviewedMark method.
		FileReviewedMark []struct {
		}
		// FileStatusMark holds details about calls to the FileStatusMark method.
		FileStatusMark []struct {
			// Status is the status argument value.
			Status diff.FileStatus
		}
		// StatusBarSeparator holds details about calls to the StatusBarSeparator method.
		StatusBarSeparator []struct {
		}
	}
	lockAnnotationInline   sync.RWMutex
	lockDiffCursor         sync.RWMutex
	lockFileAnnotationMark sync.RWMutex
	lockFileReviewedMark   sync.RWMutex
	lockFileStatusMark     sync.RWMutex
	lockStatusBarSeparator sync.RWMutex
}

// AnnotationInline calls AnnotationInlineFunc.
func (mock *styleRendererMock) AnnotationInline(text string) string {
	if mock.AnnotationInlineFunc == nil {
		panic("styleRendererMock.AnnotationInlineFunc: method is nil but styleRenderer.AnnotationInline was just called")
	}
	callInfo := struct {
		Text string
	}{
		Text: text,
	}
	mock.lockAnnotationInline.Lock()
	mock.calls.AnnotationInline = append(mock.calls.AnnotationInline, callInfo)
	mock.lockAnnotationInline.Unlock()
	return mock.AnnotationInlineFunc(text)
}

// AnnotationInlineCalls gets all the calls that were made to AnnotationInline.
// Check the length with:
//
//	len(mockedstyleRenderer.AnnotationInlineCalls())
func (mock *styleRendererMock) AnnotationInlineCalls() []struct {
	Text string
} {
	var calls []struct {
		Text string
	}
	mock.lockAnnotationInline.RLock()
	calls = mock.calls.AnnotationInline
	mock.lockAnnotationInline.RUnlock()
	return calls
}

// DiffCursor calls DiffCursorFunc.
func (mock *styleRendererMock) DiffCursor(noColors bool) string {
	if mock.DiffCursorFunc == nil {
		panic("styleRendererMock.DiffCursorFunc: method is nil but styleRenderer.DiffCursor was just called")
	}
	callInfo := struct {
		NoColors bool
	}{
		NoColors: noColors,
	}
	mock.lockDiffCursor.Lock()
	mock.calls.DiffCursor = append(mock.calls.DiffCursor, callInfo)
	mock.lockDiffCursor.Unlock()
	return mock.DiffCursorFunc(noColors)
}

// DiffCursorCalls gets all the calls that were made to DiffCursor.
// Check the length with:
//
//	len(mockedstyleRenderer.DiffCursorCalls())
func (mock *styleRendererMock) DiffCursorCalls() []struct {
	NoColors bool
} {
	var calls []struct {
		NoColors bool
	}
	mock.lockDiffCursor.RLock()
	calls = mock.calls.DiffCursor
	mock.lockDiffCursor.RUnlock()
	return calls
}

// FileAnnotationMark calls FileAnnotationMarkFunc.
func (mock *styleRendererMock) FileAnnotationMark() string {
	if mock.FileAnnotationMarkFunc == nil {
		panic("styleRendererMock.FileAnnotationMarkFunc: method is nil but styleRenderer.FileAnnotationMark was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFileAnnotationMark.Lock()
	mock.calls.FileAnnotationMark = append(mock.calls.FileAnnotationMark, callInfo)
	mock.lockFileAnnotationMark.Unlock()
	return mock.FileAnnotationMarkFunc()
}

// FileAnnotationMarkCalls gets all the calls that were made to FileAnnotationMark.
// Check the length with:
//
//	len(mockedstyleRenderer.FileAnnotationMarkCalls())
func (mock *styleRendererMock) FileAnnotationMarkCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFileAnnotationMark.RLock()
	calls = mock.calls.FileAnnotationMark
	mock.lockFileAnnotationMark.RUnlock()
	return calls
}

// FileReviewedMark calls FileReviewedMarkFunc.
func (mock *styleRendererMock) FileReviewedMark() string {
	if mock.FileReviewedMarkFunc == nil {
		panic("styleRendererMock.FileReviewedMarkFunc: method is nil but styleRenderer.FileReviewedMark was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFileReviewedMark.Lock()
	mock.calls.FileReviewedMark = append(mock.calls.FileReviewedMark, callInfo)
	mock.lockFileReviewedMark.Unlock()
	return mock.FileReviewedMarkFunc()
}

// FileReviewedMarkCalls gets all the calls that were made to FileReviewedMark.
// Check the length with:
//
//	len(mockedstyleRenderer.FileReviewedMarkCalls())
func (mock *styleRendererMock) FileReviewedMarkCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFileReviewedMark.RLock()
	calls = mock.calls.FileReviewedMark
	mock.lockFileReviewedMark.RUnlock()
	return calls
}

// FileStatusMark calls FileStatusMarkFunc.
func (mock *styleRendererMock) FileStatusMark(status diff.FileStatus) string {
	if mock.FileStatusMarkFunc == nil {
		panic("styleRendererMock.FileStatusMarkFunc: method is nil but styleRenderer.FileStatusMark was just called")
	}
	callInfo := struct {
		Status diff.FileStatus
	}{
		Status: status,
	}
	mock.lockFileStatusMark.Lock()
	mock.calls.FileStatusMark = append(mock.calls.FileStatusMark, callInfo)
	mock.lockFileStatusMark.Unlock()
	return mock.FileStatusMarkFunc(status)
}

// FileStatusMarkCalls gets all the calls that were made to FileStatusMark.
// Check the length with:
//
//	len(mockedstyleRenderer.FileStatusMarkCalls())
func (mock *styleRendererMock) FileStatusMarkCalls() []struct {
	Status diff.FileStatus
} {
	var calls []struct {
		Status diff.FileStatus
	}
	mock.lockFileStatusMark.RLock()
	calls = mock.calls.FileStatusMark
	mock.lockFileStatusMark.RUnlock()
	return calls
}

// StatusBarSeparator calls StatusBarSeparatorFunc.
func (mock *styleRendererMock) StatusBarSeparator() string {
	if mock.StatusBarSeparatorFunc == nil {
		panic("styleRendererMock.StatusBarSeparatorFunc: method is nil but styleRenderer.StatusBarSeparator was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStatusBarSeparator.Lock()
	mock.calls.StatusBarSeparator = append(mock.calls.StatusBarSeparator, callInfo)
	mock.lockStatusBarSeparator.Unlock()
	return mock.StatusBarSeparatorFunc()
}

// StatusBarSeparatorCalls gets all the calls that were made to StatusBarSeparator.
// Check the length with:
//
//	len(mockedstyleRenderer.StatusBarSeparatorCalls())
func (mock *styleRendererMock) StatusBarSeparatorCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStatusBarSeparator.RLock()
	calls = mock.calls.StatusBarSeparator
	mock.lockStatusBarSeparator.RUnlock()
	return calls
}
