// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/charmbracelet/lipgloss"
	"github.com/umputun/revdiff/app/diff"
	"github.com/umputun/revdiff/app/ui/style"
)

// styleResolverMock is a mock implementation of ui.styleResolver.
//
//	func TestSomethingThatUsesstyleResolver(t *testing.T) {
//
//		// make and configure a mocked ui.styleResolver
//		mockedstyleResolver := &styleResolverMock{
//			ColorFunc: func(k style.ColorKey) style.Color {
//				panic("mock out the Color method")
//			},
//			IndicatorBgFunc: func(change diff.ChangeType) style.Color {
//				panic("mock out the IndicatorBg method")
//			},
//			LineBgFunc: func(change diff.ChangeType) style.Color {
//				panic("mock out the LineBg method")
//			},
//			LineFgFunc: func(change diff.ChangeType) style.Color {
//				panic("mock out the LineFg method")
//			},
//			LineStyleFunc: func(change diff.ChangeType, highlighted bool) lipgloss.Style {
//				panic("mock out the LineStyle method")
//			},
//			StyleFunc: func(k style.StyleKey) lipgloss.Style {
//				panic("mock out the Style method")
//			},
//			WordDiffBgFunc: func(change diff.ChangeType) style.Color {
//				panic("mock out the WordDiffBg method")
//			},
//		}
//
//		// use mockedstyleResolver in code that requires ui.styleResolver
//		// and then make assertions.
//
//	}
type styleResolverMock struct {
	// ColorFunc mocks the Color method.
	ColorFunc func(k style.ColorKey) style.Color

	// IndicatorBgFunc mocks the IndicatorBg method.
	IndicatorBgFunc func(change diff.ChangeType) style.Color

	// LineBgFunc mocks the LineBg method.
	LineBgFunc func(change diff.ChangeType) style.Color

	// LineFgFunc mocks the LineFg method.
	LineFgFunc func(change diff.ChangeType) style.Color

	// LineStyleFunc mocks the LineStyle method.
	LineStyleFunc func(change diff.ChangeType, highlighted bool) lipgloss.Style

	// StyleFunc mocks the Style method.
	StyleFunc func(k style.StyleKey) lipgloss.Style

	// WordDiffBgFunc mocks the WordDiffBg method.
	WordDiffBgFunc func(change diff.ChangeType) style.Color

	// calls tracks calls to the methods.
	calls struct {
		// Color holds details about calls to the Color method.
		Color []struct {
			// K is the k argument value.
			K style.ColorKey
		}
		// IndicatorBg holds details about calls to the IndicatorBg method.
		IndicatorBg []struct {
			// Change is the change argument value.
			Change diff.ChangeType
		}
		// LineBg holds details about calls to the LineBg method.
		LineBg []struct {
			// Change is the change argument value.
			Change diff.ChangeType
		}
		// LineFg holds details about calls to the LineFg method.
		LineFg []struct {
			// Change is the change argument value.
			Change diff.ChangeType
		}
		// LineStyle holds details about calls to the LineStyle method.
		LineStyle []struct {
			// Change is the change argument value.
			Change diff.ChangeType
			// Highlighted is the highlighted argument value.
			Highlighted bool
		}
		// Style holds details about calls to the Style method.
		Style []struct {
			// K is the k argument value.
			K style.StyleKey
		}
		// WordDiffBg holds details about calls to the WordDiffBg method.
		WordDiffBg []struct {
			// Change is the change argument value.
			Change diff.ChangeType
		}
	}
	lockColor       sync.RWMutex
	lockIndicatorBg sync.RWMutex
	lockLineBg      sync.RWMutex
	lockLineFg      sync.RWMutex
	lockLineStyle   sync.RWMutex
	lockStyle       sync.RWMutex
	lockWordDiffBg  sync.RWMutex
}

// Color calls ColorFunc.
func (mock *styleResolverMock) Color(k style.ColorKey) style.Color {
	if mock.ColorFunc == nil {
		panic("styleResolverMock.ColorFunc: method is nil but styleResolver.Color was just called")
	}
	callInfo := struct {
		K style.ColorKey
	}{
		K: k,
	}
	mock.lockColor.Lock()
	mock.calls.Color = append(mock.calls.Color, callInfo)
	mock.lockColor.Unlock()
	return mock.ColorFunc(k)
}

// ColorCalls gets all the calls that were made to Color.
// Check the length with:
//
//	len(mockedstyleResolver.ColorCalls())
func (mock *styleResolverMock) ColorCalls() []struct {
	K style.ColorKey
} {
	var calls []struct {
		K style.ColorKey
	}
	mock.lockColor.RLock()
	calls = mock.calls.Color
	mock.lockColor.RUnlock()
	return calls
}

// IndicatorBg calls IndicatorBgFunc.
func (mock *styleResolverMock) IndicatorBg(change diff.ChangeType) style.Color {
	if mock.IndicatorBgFunc == nil {
		panic("styleResolverMock.IndicatorBgFunc: method is nil but styleResolver.IndicatorBg was just called")
	}
	callInfo := struct {
		Change diff.ChangeType
	}{
		Change: change,
	}
	mock.lockIndicatorBg.Lock()
	mock.calls.IndicatorBg = append(mock.calls.IndicatorBg, callInfo)
	mock.lockIndicatorBg.Unlock()
	return mock.IndicatorBgFunc(change)
}

// IndicatorBgCalls gets all the calls that were made to IndicatorBg.
// Check the length with:
//
//	len(mockedstyleResolver.IndicatorBgCalls())
func (mock *styleResolverMock) IndicatorBgCalls() []struct {
	Change diff.ChangeType
} {
	var calls []struct {
		Change diff.ChangeType
	}
	mock.lockIndicatorBg.RLock()
	calls = mock.calls.IndicatorBg
	mock.lockIndicatorBg.RUnlock()
	return calls
}

// LineBg calls LineBgFunc.
func (mock *styleResolverMock) LineBg(change diff.ChangeType) style.Color {
	if mock.LineBgFunc == nil {
		panic("styleResolverMock.LineBgFunc: method is nil but styleResolver.LineBg was just called")
	}
	callInfo := struct {
		Change diff.ChangeType
	}{
		Change: change,
	}
	mock.lockLineBg.Lock()
	mock.calls.LineBg = append(mock.calls.LineBg, callInfo)
	mock.lockLineBg.Unlock()
	return mock.LineBgFunc(change)
}

// LineBgCalls gets all the calls that were made to LineBg.
// Check the length with:
//
//	len(mockedstyleResolver.LineBgCalls())
func (mock *styleResolverMock) LineBgCalls() []struct {
	Change diff.ChangeType
} {
	var calls []struct {
		Change diff.ChangeType
	}
	mock.lockLineBg.RLock()
	calls = mock.calls.LineBg
	mock.lockLineBg.RUnlock()
	return calls
}

// LineFg calls LineFgFunc.
func (mock *styleResolverMock) LineFg(change diff.ChangeType) style.Color {
	if mock.LineFgFunc == nil {
		panic("styleResolverMock.LineFgFunc: method is nil but styleResolver.LineFg was just called")
	}
	callInfo := struct {
		Change diff.ChangeType
	}{
		Change: change,
	}
	mock.lockLineFg.Lock()
	mock.calls.LineFg = append(mock.calls.LineFg, callInfo)
	mock.lockLineFg.Unlock()
	return mock.LineFgFunc(change)
}

// LineFgCalls gets all the calls that were made to LineFg.
// Check the length with:
//
//	len(mockedstyleResolver.LineFgCalls())
func (mock *styleResolverMock) LineFgCalls() []struct {
	Change diff.ChangeType
} {
	var calls []struct {
		Change diff.ChangeType
	}
	mock.lockLineFg.RLock()
	calls = mock.calls.LineFg
	mock.lockLineFg.RUnlock()
	return calls
}

// LineStyle calls LineStyleFunc.
func (mock *styleResolverMock) LineStyle(change diff.ChangeType, highlighted bool) lipgloss.Style {
	if mock.LineStyleFunc == nil {
		panic("styleResolverMock.LineStyleFunc: method is nil but styleResolver.LineStyle was just called")
	}
	callInfo := struct {
		Change      diff.ChangeType
		Highlighted bool
	}{
		Change:      change,
		Highlighted: highlighted,
	}
	mock.lockLineStyle.Lock()
	mock.calls.LineStyle = append(mock.calls.LineStyle, callInfo)
	mock.lockLineStyle.Unlock()
	return mock.LineStyleFunc(change, highlighted)
}

// LineStyleCalls gets all the calls that were made to LineStyle.
// Check the length with:
//
//	len(mockedstyleResolver.LineStyleCalls())
func (mock *styleResolverMock) LineStyleCalls() []struct {
	Change      diff.ChangeType
	Highlighted bool
} {
	var calls []struct {
		Change      diff.ChangeType
		Highlighted bool
	}
	mock.lockLineStyle.RLock()
	calls = mock.calls.LineStyle
	mock.lockLineStyle.RUnlock()
	return calls
}

// Style calls StyleFunc.
func (mock *styleResolverMock) Style(k style.StyleKey) lipgloss.Style {
	if mock.StyleFunc == nil {
		panic("styleResolverMock.StyleFunc: method is nil but styleResolver.Style was just called")
	}
	callInfo := struct {
		K style.StyleKey
	}{
		K: k,
	}
	mock.lockStyle.Lock()
	mock.calls.Style = append(mock.calls.Style, callInfo)
	mock.lockStyle.Unlock()
	return mock.StyleFunc(k)
}

// StyleCalls gets all the calls that were made to Style.
// Check the length with:
//
//	len(mockedstyleResolver.StyleCalls())
func (mock *styleResolverMock) StyleCalls() []struct {
	K style.StyleKey
} {
	var calls []struct {
		K style.StyleKey
	}
	mock.lockStyle.RLock()
	calls = mock.calls.Style
	mock.lockStyle.RUnlock()
	return calls
}

// WordDiffBg calls WordDiffBgFunc.
func (mock *styleResolverMock) WordDiffBg(change diff.ChangeType) style.Color {
	if mock.WordDiffBgFunc == nil {
		panic("styleResolverMock.WordDiffBgFunc: method is nil but styleResolver.WordDiffBg was just called")
	}
	callInfo := struct {
		Change diff.ChangeType
	}{
		Change: change,
	}
	mock.lockWordDiffBg.Lock()
	mock.calls.WordDiffBg = append(mock.calls.WordDiffBg, callInfo)
	mock.lockWordDiffBg.Unlock()
	return mock.WordDiffBgFunc(change)
}

// WordDiffBgCalls gets all the calls that were made to WordDiffBg.
// Check the length with:
//
//	len(mockedstyleResolver.WordDiffBgCalls())
func (mock *styleResolverMock) WordDiffBgCalls() []struct {
	Change diff.ChangeType
} {
	var calls []struct {
		Change diff.ChangeType
	}
	mock.lockWordDiffBg.RLock()
	calls = mock.calls.WordDiffBg
	mock.lockWordDiffBg.RUnlock()
	return calls
}
