// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/app/diff"
)

// SyntaxHighlighterMock is a mock implementation of ui.SyntaxHighlighter.
//
//	func TestSomethingThatUsesSyntaxHighlighter(t *testing.T) {
//
//		// make and configure a mocked ui.SyntaxHighlighter
//		mockedSyntaxHighlighter := &SyntaxHighlighterMock{
//			HighlightLinesFunc: func(filename string, lines []diff.DiffLine) []string {
//				panic("mock out the HighlightLines method")
//			},
//			SetStyleFunc: func(styleName string) bool {
//				panic("mock out the SetStyle method")
//			},
//			StyleNameFunc: func() string {
//				panic("mock out the StyleName method")
//			},
//		}
//
//		// use mockedSyntaxHighlighter in code that requires ui.SyntaxHighlighter
//		// and then make assertions.
//
//	}
type SyntaxHighlighterMock struct {
	// HighlightLinesFunc mocks the HighlightLines method.
	HighlightLinesFunc func(filename string, lines []diff.DiffLine) []string

	// SetStyleFunc mocks the SetStyle method.
	SetStyleFunc func(styleName string) bool

	// StyleNameFunc mocks the StyleName method.
	StyleNameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// HighlightLines holds details about calls to the HighlightLines method.
		HighlightLines []struct {
			// Filename is the filename argument value.
			Filename string
			// Lines is the lines argument value.
			Lines []diff.DiffLine
		}
		// SetStyle holds details about calls to the SetStyle method.
		SetStyle []struct {
			// StyleName is the styleName argument value.
			StyleName string
		}
		// StyleName holds details about calls to the StyleName method.
		StyleName []struct {
		}
	}
	lockHighlightLines sync.RWMutex
	lockSetStyle       sync.RWMutex
	lockStyleName      sync.RWMutex
}

// HighlightLines calls HighlightLinesFunc.
func (mock *SyntaxHighlighterMock) HighlightLines(filename string, lines []diff.DiffLine) []string {
	if mock.HighlightLinesFunc == nil {
		panic("SyntaxHighlighterMock.HighlightLinesFunc: method is nil but SyntaxHighlighter.HighlightLines was just called")
	}
	callInfo := struct {
		Filename string
		Lines    []diff.DiffLine
	}{
		Filename: filename,
		Lines:    lines,
	}
	mock.lockHighlightLines.Lock()
	mock.calls.HighlightLines = append(mock.calls.HighlightLines, callInfo)
	mock.lockHighlightLines.Unlock()
	return mock.HighlightLinesFunc(filename, lines)
}

// HighlightLinesCalls gets all the calls that were made to HighlightLines.
// Check the length with:
//
//	len(mockedSyntaxHighlighter.HighlightLinesCalls())
func (mock *SyntaxHighlighterMock) HighlightLinesCalls() []struct {
	Filename string
	Lines    []diff.DiffLine
} {
	var calls []struct {
		Filename string
		Lines    []diff.DiffLine
	}
	mock.lockHighlightLines.RLock()
	calls = mock.calls.HighlightLines
	mock.lockHighlightLines.RUnlock()
	return calls
}

// SetStyle calls SetStyleFunc.
func (mock *SyntaxHighlighterMock) SetStyle(styleName string) bool {
	if mock.SetStyleFunc == nil {
		panic("SyntaxHighlighterMock.SetStyleFunc: method is nil but SyntaxHighlighter.SetStyle was just called")
	}
	callInfo := struct {
		StyleName string
	}{
		StyleName: styleName,
	}
	mock.lockSetStyle.Lock()
	mock.calls.SetStyle = append(mock.calls.SetStyle, callInfo)
	mock.lockSetStyle.Unlock()
	return mock.SetStyleFunc(styleName)
}

// SetStyleCalls gets all the calls that were made to SetStyle.
// Check the length with:
//
//	len(mockedSyntaxHighlighter.SetStyleCalls())
func (mock *SyntaxHighlighterMock) SetStyleCalls() []struct {
	StyleName string
} {
	var calls []struct {
		StyleName string
	}
	mock.lockSetStyle.RLock()
	calls = mock.calls.SetStyle
	mock.lockSetStyle.RUnlock()
	return calls
}

// StyleName calls StyleNameFunc.
func (mock *SyntaxHighlighterMock) StyleName() string {
	if mock.StyleNameFunc == nil {
		panic("SyntaxHighlighterMock.StyleNameFunc: method is nil but SyntaxHighlighter.StyleName was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStyleName.Lock()
	mock.calls.StyleName = append(mock.calls.StyleName, callInfo)
	mock.lockStyleName.Unlock()
	return mock.StyleNameFunc()
}

// StyleNameCalls gets all the calls that were made to StyleName.
// Check the length with:
//
//	len(mockedSyntaxHighlighter.StyleNameCalls())
func (mock *SyntaxHighlighterMock) StyleNameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStyleName.RLock()
	calls = mock.calls.StyleName
	mock.lockStyleName.RUnlock()
	return calls
}
