// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/revdiff/app/ui/worddiff"
)

// wordDifferMock is a mock implementation of ui.wordDiffer.
//
//	func TestSomethingThatUseswordDiffer(t *testing.T) {
//
//		// make and configure a mocked ui.wordDiffer
//		mockedwordDiffer := &wordDifferMock{
//			ComputeIntraRangesFunc: func(minusLine string, plusLine string) ([]worddiff.Range, []worddiff.Range) {
//				panic("mock out the ComputeIntraRanges method")
//			},
//			InsertHighlightMarkersFunc: func(s string, matches []worddiff.Range, hlOn string, hlOff string) string {
//				panic("mock out the InsertHighlightMarkers method")
//			},
//			PairLinesFunc: func(lines []worddiff.LinePair) []worddiff.Pair {
//				panic("mock out the PairLines method")
//			},
//		}
//
//		// use mockedwordDiffer in code that requires ui.wordDiffer
//		// and then make assertions.
//
//	}
type wordDifferMock struct {
	// ComputeIntraRangesFunc mocks the ComputeIntraRanges method.
	ComputeIntraRangesFunc func(minusLine string, plusLine string) ([]worddiff.Range, []worddiff.Range)

	// InsertHighlightMarkersFunc mocks the InsertHighlightMarkers method.
	InsertHighlightMarkersFunc func(s string, matches []worddiff.Range, hlOn string, hlOff string) string

	// PairLinesFunc mocks the PairLines method.
	PairLinesFunc func(lines []worddiff.LinePair) []worddiff.Pair

	// calls tracks calls to the methods.
	calls struct {
		// ComputeIntraRanges holds details about calls to the ComputeIntraRanges method.
		ComputeIntraRanges []struct {
			// MinusLine is the minusLine argument value.
			MinusLine string
			// PlusLine is the plusLine argument value.
			PlusLine string
		}
		// InsertHighlightMarkers holds details about calls to the InsertHighlightMarkers method.
		InsertHighlightMarkers []struct {
			// S is the s argument value.
			S string
			// Matches is the matches argument value.
			Matches []worddiff.Range
			// HlOn is the hlOn argument value.
			HlOn string
			// HlOff is the hlOff argument value.
			HlOff string
		}
		// PairLines holds details about calls to the PairLines method.
		PairLines []struct {
			// Lines is the lines argument value.
			Lines []worddiff.LinePair
		}
	}
	lockComputeIntraRanges     sync.RWMutex
	lockInsertHighlightMarkers sync.RWMutex
	lockPairLines              sync.RWMutex
}

// ComputeIntraRanges calls ComputeIntraRangesFunc.
func (mock *wordDifferMock) ComputeIntraRanges(minusLine string, plusLine string) ([]worddiff.Range, []worddiff.Range) {
	if mock.ComputeIntraRangesFunc == nil {
		panic("wordDifferMock.ComputeIntraRangesFunc: method is nil but wordDiffer.ComputeIntraRanges was just called")
	}
	callInfo := struct {
		MinusLine string
		PlusLine  string
	}{
		MinusLine: minusLine,
		PlusLine:  plusLine,
	}
	mock.lockComputeIntraRanges.Lock()
	mock.calls.ComputeIntraRanges = append(mock.calls.ComputeIntraRanges, callInfo)
	mock.lockComputeIntraRanges.Unlock()
	return mock.ComputeIntraRangesFunc(minusLine, plusLine)
}

// ComputeIntraRangesCalls gets all the calls that were made to ComputeIntraRanges.
// Check the length with:
//
//	len(mockedwordDiffer.ComputeIntraRangesCalls())
func (mock *wordDifferMock) ComputeIntraRangesCalls() []struct {
	MinusLine string
	PlusLine  string
} {
	var calls []struct {
		MinusLine string
		PlusLine  string
	}
	mock.lockComputeIntraRanges.RLock()
	calls = mock.calls.ComputeIntraRanges
	mock.lockComputeIntraRanges.RUnlock()
	return calls
}

// InsertHighlightMarkers calls InsertHighlightMarkersFunc.
func (mock *wordDifferMock) InsertHighlightMarkers(s string, matches []worddiff.Range, hlOn string, hlOff string) string {
	if mock.InsertHighlightMarkersFunc == nil {
		panic("wordDifferMock.InsertHighlightMarkersFunc: method is nil but wordDiffer.InsertHighlightMarkers was just called")
	}
	callInfo := struct {
		S       string
		Matches []worddiff.Range
		HlOn    string
		HlOff   string
	}{
		S:       s,
		Matches: matches,
		HlOn:    hlOn,
		HlOff:   hlOff,
	}
	mock.lockInsertHighlightMarkers.Lock()
	mock.calls.InsertHighlightMarkers = append(mock.calls.InsertHighlightMarkers, callInfo)
	mock.lockInsertHighlightMarkers.Unlock()
	return mock.InsertHighlightMarkersFunc(s, matches, hlOn, hlOff)
}

// InsertHighlightMarkersCalls gets all the calls that were made to InsertHighlightMarkers.
// Check the length with:
//
//	len(mockedwordDiffer.InsertHighlightMarkersCalls())
func (mock *wordDifferMock) InsertHighlightMarkersCalls() []struct {
	S       string
	Matches []worddiff.Range
	HlOn    string
	HlOff   string
} {
	var calls []struct {
		S       string
		Matches []worddiff.Range
		HlOn    string
		HlOff   string
	}
	mock.lockInsertHighlightMarkers.RLock()
	calls = mock.calls.InsertHighlightMarkers
	mock.lockInsertHighlightMarkers.RUnlock()
	return calls
}

// PairLines calls PairLinesFunc.
func (mock *wordDifferMock) PairLines(lines []worddiff.LinePair) []worddiff.Pair {
	if mock.PairLinesFunc == nil {
		panic("wordDifferMock.PairLinesFunc: method is nil but wordDiffer.PairLines was just called")
	}
	callInfo := struct {
		Lines []worddiff.LinePair
	}{
		Lines: lines,
	}
	mock.lockPairLines.Lock()
	mock.calls.PairLines = append(mock.calls.PairLines, callInfo)
	mock.lockPairLines.Unlock()
	return mock.PairLinesFunc(lines)
}

// PairLinesCalls gets all the calls that were made to PairLines.
// Check the length with:
//
//	len(mockedwordDiffer.PairLinesCalls())
func (mock *wordDifferMock) PairLinesCalls() []struct {
	Lines []worddiff.LinePair
} {
	var calls []struct {
		Lines []worddiff.LinePair
	}
	mock.lockPairLines.RLock()
	calls = mock.calls.PairLines
	mock.lockPairLines.RUnlock()
	return calls
}
